#!/bin/sh

# Nuke the wifi device block
# This will allow the host ap to work
rfkill unblock wlan

# Start carflix app
cd /home/pi/carflix
./carflix --bind :80 >/dev/null 2>&1 &

# Might be able to switch post-boot
# This would protect the SD card
##  mount -o remount,ro /
##  mount -o remount,ro /boot

exit 0
